### PR TITLE
Refactor error returns

### PR DESCRIPTION
**Pull request by jancona**
Eliminate `persist` errors and make persistence interfaces return `*model.Error`.

This is pretty invasive, so I pushed it on a separate branch. I was running into a number of inconsistencies in what kind of error we returned in different situations. Making everything a `model.Error` is one way to resolve it, and I think I like the result, but I'm interested in whether you agree.

### CODE REVIEW

**Comment by jancona** [comment]
I had run into some issues with `nil` interface values and ran across this [Go FAQ entry](https://golang.org/doc/faq#nil_error) which says "It's a good idea for functions that return errors always to use the error type in their signature..." I figured out a way to switch the `persist` methods back to returning `error`, but keep most of the benefits of using `model.Error`.

**Comment by DallanQ** [comment]
This is definitely a step towards making error handling easier to understand. Is the following understanding correct?

* at the model layer we have NewError(code, params)
* at the api layer we have NewErrors(code, err) and NewErrorsFromError(model.Error)

It seems like NewErrors and NewErrorsFromError. In fact it appears if i pass a model.Error into NewErrors, then  NewErrors behaves like NewErrorsFromError. If that's the case, would it make sense to combine the functions into a single api.NewError(code, err) function? Also, is it useful for an api.Error to hold an array of model.Error vs just an array of error? I'm not opposed to what you're doing at all; I'm trying to make sure I understand it so I use it correctly.

**Comment by jancona** [comment]
Note that the code passed to `model.NewError` isn't an HTTP status code, it's an `ErrorCode` that has an associated message and expected parameters, so that the client can get useful information out of it.

Because `model.Error` includes the ErrorCode, that can be used to determine the correct HTTP status code, so you don't have to pass a status code to `NewErrorsFromError`. `NewErrors` calls `NewErrorsFromError` if you send it a `model.Error`. In that case the HTTP status is ignored and you can just send it a zero. So we could eliminate `NewErrorsFromError` (or make it private) and just call `NewErrors(0, modelError)` if you like that better.

`api.Errors` can hold multiple errors because validation can return multiple errors. So if you're missing multiple required fields or have other problems the returned error will include all the information.

So theoretically this allows the client to do useful things with the returned error info. You're writing the client: Is any of this useful to you? If the answer is no, maybe this is all needless complexity.

**Comment by DallanQ** [comment]
I knew that the model contained a model error code and it makes sense that model errors wouldn't be http codes. I like the idea that if api.NewErrors is passed in a model.Error, then it sets the httpStatus from that. I think if NewErrorsFromError were private and we just called NewErrors it would simplify things.

How do you feel about renaming api.NewErrors to api.NewError ? I know that it can hold multiple errors, but it still returns an object that implements the "error" interface. I think calling it api.NewError and renaming the struct from Errors to just Error makes that more obvious. What do you think?

The client automatically retries network and server errors and does not attempt to retry 4xx errors. Currently all it does is display the error message on the screen to the user.

**Comment by jancona** [comment]
So I made the changes you suggested:

* Rename NewErrors -> NewError
* Make NewErrorFromErrors private--I also renamed it to fromErrors

Then I got to thinking. in `api.NewError` there are three kinds of things that can be passed:
* `model.Error` which includes a code that determines the HTTP status.
* Generic `error`. This is always a 500 status.
* `ValidationError` which is always a 400.

So I eliminated the httpStatus parameter. The only place this will be a problem is if we wanted to do some odd HTTP status/message combination. If that happens, we can either create a new model.ErrorCode, or add a new function with both parameters. But if we don't have any so far we may never need it.

**Comment by DallanQ** [comment]
I like it! thank you!

**Pull request merged**
