### PR TITLE
add cors

### PR DESCRIPTION
**Pull request by DallanQ**
I learned something about API Gateway's CORS support the other day. It appears that if you have a * endpoint it doesn't automatically answer the OPTIONS request. I suppose in hindsight that makes sense - it doesn't know if the endpoint being requested even exists.

We had added CORS support when running locally, but not when running under lambda. So I made CORS a middleware.

I also learned something about gorilla mux. Gorilla doesn't call middleware functions unless the path *and method* match an existing route. So I had to add OPTIONS as additional methods on all of the routes.

### CODE REVIEW

**Comment by jancona** [comment]
Do you return a GET body to an OPTIONS request? Is that correct?

**Comment by DallanQ** [comment]
You're not supposed to, but I verified that the gorilla CORS handler doesn't call "next" on an OPTIONS request. I just needs an endpoint. We could create separate routes for the OPTION methods with dummy handlers. Would that be clearer?

**Comment by jancona** [comment]
So does Gorilla not actually return the body? I don't feel strongly about it but it seemed a bit weird. Perhaps a comment at least?

**Comment by DallanQ** [comment]
that's right. I'll make separate routes. It seemed odd (unexpected) to me as well.

**Comment by DallanQ** [comment]
what do you think?

**Pull request merged**
