### PR TITLE
Partial implementation of short unit tests in the main package

### PR DESCRIPTION
**Pull request by jancona**
I'd like to get rid of the tests in the `main` package that depend on the database, since it seems like the `api` package is a better place for them. [categories_short_test.go](https://github.com/OurRootsOrg/cms-server/blob/httptest/server/categories_short_test.go) is an example of a way to do that. Does this seem like a productive approach? Testify has a `mock` package that could be added, but I'm not sure it's necessary in this case. If I continue with this, I would get rid of the current tests in that package that depend on Postgres.

### CODE REVIEW

**Comment by DallanQ** [comment]
Since the main package should really just test encoding and decoding, I like where you are going with this. But apiMock.AddCategory needs to return a category that can be encoded by a json encoder, correct? Wouldn't you need to add a mockCategoryResult object to the apiMock struct and return that?  This code snippet returns an error for example: https://play.golang.org/p/vC2NR2cBEhe

**Comment by jancona** [comment]
I'm not sure I understand your question. Your example returns an error because of ["typed nils"](https://golang.org/doc/faq#nil_error). You can work around that error with something like this: https://play.golang.org/p/_B2uTzWqSHk But to marshal valid JSON, you'd have to give it Category object, not a nil pointer. Or did I miss your point completely?

**Comment by DallanQ** [comment]
I'm looking at what apiMock.AddCollection returns: a.result.(*model.
Collection) and I'm wondering how that will work with line 95 in
server/collections.go: err = enc.Encode(collection)

I'm probably misunderstanding something.

**Comment by jancona** [comment]
Ah, now I understand! You're talking about the case where the test calls PostCollect, which in turn calls AddCollection. I'm pretty sure that requires using the `testify/mock` stuff. Let me give that a try.

**Comment by jancona** [comment]
Actually, I think I confused myself. :-) In any case, everything seems to work the way I was doing things. I've completed short tests for all the endpoints, including content and posts.

**Comment by DallanQ** [comment]
Ah, I see. This is the part I was missing, where you set the mock api result to an object of the right type before POST'ing

	am.result = &model.Collection{
		ID:             "/collections/1",
		CollectionIn:   in,
		InsertTime:     now,
		LastUpdateTime: now,
	}

**Pull request merged**
